### ISSUE TITLE
Separating stylus files

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#11]
Hello again!

I have a duplication of CSS becouse files with @import сombining. How can I compile only one index stylus file?

![dublicate](https://user-images.githubusercontent.com/11922258/28181966-0b8ae034-6813-11e7-8b4d-98cbe6f7ab9b.PNG)

**Comment by jh3y** [comment]
Hey @scoutrul 

This is an expected side effect of how I've set up the build task. The reason that styles are being duplicated is because all `.styl` files within the `src/style` directory are being concatenated before being processed with `stylus`.

This can be seen in this line; https://github.com/jh3y/gulp-boilerplate/blob/master/build-tasks/styles.js#L20

```js
.pipe(plugins.concat(gConfig.pkg.name + '.stylus'))
```

The way to alter the behaviour to how you desire would be to remove that line from the task and then update the source path here; https://github.com/jh3y/gulp-boilerplate/blob/master/gulp-config.js#L56 to just look for the one root style file instead of all files under `src/style`.

```js
styles   : 'src/style/style.styl', // NOT 'src/style/**/*.styl'
```

Hope that helps! 👍

**Comment by scoutrul** [comment]
Yes, I got it! 
Thank you!

**Comment by jh3y** [comment]
Did you stop `gulp` and then restart it after making changes? It might also be best to clear out the `public` folder.

Is it your intention to nest those styles under `#app`? That could lead to some long style rules.

Also, you may need to declare a new path such as `watch_styles` or `compile_style` because if you change to purely use `src/style/style.styl` as the source, it will only watch for changes in that one file and not watch your other files.

**Comment by scoutrul** [comment]
It was just file names mistake, sorry for that

**Comment by jh3y** [comment]
No worries, glad you got it sorted 😄 👍
