### ISSUE TITLE
gulp-autoprefixer is not perfect

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#13]
Hello! I found a problem with gulp-autoprefixer which have bad browser support. For exemple you can't 
make a `display: -webkit-flexbox` prefix which need for safari4 (iphone 4++).
For solve this problem i did use the postcss plugin.
Just for you know.

**Comment by jh3y** [comment]
Hey @scoutrul 

That's not actually an issue. It would just need the configuration updated to include the versions desired. The configuration for `gulp-autoprefixer` in this boilerplate is;

```js
prefix: [
      'last 3 versions',
      'Blackberry 10',
      'Android 3',
      'Android 4'
    ],
```

**Comment by scoutrul** [comment]
it is not about just configuration, it is about browser supporting by gulp-autoprefixer.
You can't do display: -webkit-flexbox with it.
Browser name: ios_saf 7
https://autoprefixer.github.io/ try online and compare with gulp-autoprefixer's output

**Comment by jh3y** [comment]
You can create that prefix how you want but I personally wouldn't add it. If I really needed it, I would just write it in because it wouldn't be worth the overhead to change the build process etc. IMHO.

It's likely to be such a small percentage of users that would even be using such an old version of `Safari` anyway and even then the prefix would have been `display: -webkit-box` for `iOS` which can easily be obtained by using `iOS 4` in the configuration.

**Comment by scoutrul** [comment]
Not display: -webkit-box, but  -webkit-flexbox.
Unfortunelly i'm in this small procentage with my iphone4S ))

**Comment by jh3y** [comment]
An iPhone 4S shouldn't be using that older version of `Safari`. It should at least be on `iOS 7/8` which would be at least `Safari 7` which doesn't require that prefix. Additionally, `-webkit-flexbox` isn't a documented prefix.

If you think there is an issue with the prefixing please raise an issue with the appropriate project.

**Comment by scoutrul** [comment]
I don't want to take much of your time, just believe me that iphone4s understand only -webkit-flexbox syntax. I know it because I have it.
